// Question generation logic for the interview engine.
// Questions are NOT static — they are generated by Claude on session start
// and saved to interview_questions table for dedup tracking.

export type QuestionCategory = 'product_sense' | 'execution_metrics' | 'behavioral' | 'strategy_design'
export type CompanyTier = 1 | 2 | 3

export const QUESTION_CATEGORIES: QuestionCategory[] = [
  'product_sense',
  'execution_metrics',
  'behavioral',
  'strategy_design',
]

export const CATEGORY_LABELS: Record<QuestionCategory, string> = {
  product_sense: 'Product Sense',
  execution_metrics: 'Execution & Metrics',
  behavioral: 'Behavioral',
  strategy_design: 'Strategy & Design',
}

// ─── Difficulty progression ───────────────────────────────────────────────────

export function getDifficultyRangeForSession(
  sessionCount: number,
  isGauntlet = false
): { min: number; max: number } {
  if (isGauntlet) return { min: 5, max: 5 }
  if (sessionCount <= 2) return { min: 1, max: 2 }
  if (sessionCount <= 4) return { min: 3, max: 4 }
  return { min: 4, max: 5 }
}

// ─── Generated question shape ─────────────────────────────────────────────────

export interface GeneratedQuestion {
  question_text: string
  category: QuestionCategory
  difficulty: number
  lp_map: string[]
  tags: string[]
}

export function parseGeneratedQuestion(raw: unknown): GeneratedQuestion | null {
  if (!raw || typeof raw !== 'object') return null
  const r = raw as Record<string, unknown>
  if (typeof r.question_text !== 'string' || !r.question_text.trim()) return null
  if (!QUESTION_CATEGORIES.includes(r.category as QuestionCategory)) return null
  if (typeof r.difficulty !== 'number') return null
  const diff = Math.round(r.difficulty)
  if (diff < 1 || diff > 5) return null
  const lpMap = Array.isArray(r.lp_map) ? r.lp_map.filter((x: unknown) => typeof x === 'string') : []
  const tags = Array.isArray(r.tags) ? r.tags.filter((x: unknown) => typeof x === 'string') : []
  return {
    question_text: r.question_text,
    category: r.category as QuestionCategory,
    difficulty: diff,
    lp_map: lpMap,
    tags,
  }
}

// ─── Deduplication ────────────────────────────────────────────────────────────

function wordOverlapRatio(a: string, b: string): number {
  const wordsA = a.toLowerCase().split(/\W+/).filter(w => w.length > 3)
  const wordsB = new Set(b.toLowerCase().split(/\W+/).filter(w => w.length > 3))
  if (wordsA.length === 0) return 0
  let overlap = 0
  for (let i = 0; i < wordsA.length; i++) {
    if (wordsB.has(wordsA[i])) overlap++
  }
  return overlap / wordsA.length
}

export function filterAskedQuestions(
  candidates: string[],
  alreadyAsked: string[],
  overlapThreshold = 0.8
): string[] {
  return candidates.filter(candidate =>
    !alreadyAsked.some(asked => wordOverlapRatio(candidate, asked) >= overlapThreshold)
  )
}

// ─── Prompt builder ───────────────────────────────────────────────────────────

export function buildQuestionPrompt(params: {
  company: string
  tier: CompanyTier
  roundType: string
  difficultyRange: { min: number; max: number }
  userAnswerHistory: string[]
  jdText: string | null
  skillGaps: Record<string, number>
  askedQuestions: string[]
  persona: string
  count?: number
}): string {
  const { company, tier, roundType, difficultyRange, userAnswerHistory,
    jdText, skillGaps, askedQuestions, persona, count = 5 } = params

  const topGaps = Object.entries(skillGaps)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 3)
    .map(([dim, gap]) => `${dim} (gap: ${gap.toFixed(1)})`)
    .join(', ')

  const askedBlock = askedQuestions.length > 0
    ? `\nDO NOT REPEAT any of these previously asked questions:\n${askedQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n')}`
    : ''

  const jdBlock = jdText
    ? `\nActive job description context (shape questions to this role):\n${jdText.slice(0, 400)}`
    : ''

  const historyBlock = userAnswerHistory.length > 0
    ? `\nUser has struggled with: ${userAnswerHistory.join('; ')}. Ask consolidation questions in those areas.`
    : ''

  const indiaContext = tier === 2
    ? '\nThis is an Indian startup/tech company. Questions should reflect speed-vs-process trade-offs, growth-stage thinking, and 0-to-1 execution context.'
    : ''

  const dedupeRule = askedQuestions.length > 0
    ? '- Each question must be distinct and not overlap with the DO NOT REPEAT list above'
    : '- Each question must be unique and not repeat common generic PM interview questions'

  return `You are a ${persona} interviewing a Senior PM (Amazon L6, Hyderabad) for a ${roundType} round at ${company}.

Generate exactly ${count} interview questions for this session.

INPUTS:
- Company: ${company} (Tier ${tier})
- Round type: ${roundType}
- Difficulty range: ${difficultyRange.min}–${difficultyRange.max} (on a 1–5 scale)
- User's top skill gaps (ask harder questions here): ${topGaps || 'none identified'}${jdBlock}${historyBlock}${indiaContext}${askedBlock}

RULES:
- Ask questions a real PM interviewer at this company would actually ask in 2026
- Mix categories: product_sense, execution_metrics, behavioral, strategy_design
- Behavioral questions must map to at least one Leadership Principle or company value
- Difficulty must be within the specified range
- ${dedupeRule}

OUTPUT: Respond with valid JSON array only — no markdown, no extra text:
[
  {
    "question_text": "<the full question as the interviewer would ask it>",
    "category": "<product_sense|execution_metrics|behavioral|strategy_design>",
    "difficulty": <1-5>,
    "lp_map": ["<LP or value name>"],
    "tags": ["<relevant skill or topic tag>"]
  }
]`
}
